---
- name: validate virtualization extensions are available to this host
  include_tasks: validate.yml
  when: not cicd_test|bool

- name: enable libvirt services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ libvirt_services }}"

- name: start tuned profile virtual-host
  shell: |
   set -o pipefail &&  tuned-adm profile virtual-host
  register: start_tuned
  changed_when: start_tuned.rc != 0
  args:
    executable: /bin/bash
- name: configure bridge interface for libvirt
  include_tasks: bridge_interface.yml
  #when: configure_bridge
  loop: "{{ libvirt_host_networks }}"
  loop_control:
    index_var: type_idx
    loop_var: bridge_item
  when: (bridge_item.mode == 'bridge' and  not cicd_test|bool and  (ansible_distribution != "Fedora" and ansible_distribution_major_version != '36'))

- name: configure bridge interface for libvirt
  ansible.builtin.import_role:
    name: linux-system-roles.network
  vars:
    network_provider: nm
    network_connections:
      - name: br0-bond0
        type: bond
        interface_name: bond0
        controller: internal-br0
        port_type: bridge
        ip:
          route_metric4: 100
          dhcp4: no
          #dhcp4_send_hostname: no
          gateway4: 192.168.1.1
          dns:
            - 192.168.1.239
            - 1.1.1.1
          dns_search:
            - tosins-lab.com
          address:
          - 192.168.1.88/24
      - name:  "br0-bond0-{{ kvm_host_interface }}"
        type: ethernet
        interface_name: "{{ kvm_host_interface }}"
        controller: br0-bond0
        port_type: bond

  when: ansible_distribution == "Fedora" and ansible_distribution_major_version == '36'

- meta: end_play
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version == '36'

- name: configure libvirt network
  loop: "{{ libvirt_host_networks }}"
  loop_control:
    index_var: libvirt_idx
    loop_var: libvirt_item
  include_tasks: networks.yml
  when: not cicd_test|bool

- name: configure libvirt storage pool
  include_tasks: storage_pool.yml
  when: not cicd_test|bool

- name: Make libvirt accessible by non-root user
  include_tasks: validate.yml
  when: enable_libvirt_admin_user|bool
