---
- name: validate virtualization extensions are available to this host
  tags: [validate_libvirt, libvirt_setup]
  include_tasks: validate.yml
  when: not cicd_test|bool

- name: enable libvirt services
  tags: [libvirt_setup, libvirt_services]
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ libvirt_services }}"

- name: start tuned profile virtual-host
  tags: [libvirt_setup, libvirt_tuned]
  shell: |
   set -o pipefail &&  tuned-adm profile virtual-host
  register: start_tuned
  changed_when: start_tuned.rc != 0
  args:
    executable: /bin/bash

- name: configure bridge interface for libvirt
  tags: [libvirt_setup, libvirt_bridge]
  include_tasks: bridge_interface.yml
  loop: "{{ libvirt_host_networks }}"
  loop_control:
    index_var: bridge_index
    loop_var: bridge_item
  when: (bridge_item.mode == 'bridge' and not cicd_test|bool)

- name: configure libvirt network
  tags: [libvirt_setup, libvirt_networks]
  loop: "{{ libvirt_host_networks }}"
  loop_control:
    index_var: libvirt_idx
    loop_var: libvirt_item
  include_tasks: networks.yml
  when: not cicd_test|bool

- name: configure libvirt storage pool
  tags: [libvirt_setup, libvirt_storage]
  import_tasks: storage_pool.yml
  when: not cicd_test|bool

- name: Make libvirt accessible by non-root user
  tags: [libvirt_setup, libvirt_user_mode]
  import_tasks: user_libvirt.yml
  when: enable_libvirt_admin_user|bool
