---
- name: Allow non-root users to libvirt unix_sock_group
  tags: [libvirt_setup, libvirt_user_mode]
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: '^#\s*unix_sock_group.*$'
    line: 'unix_sock_group = "libvirt"'
  notify: Reload libvirtd service

- name: Allow non-root users to libvirt unix_sock_rw_perms
  tags: [libvirt_setup, libvirt_user_mode]
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: '^#\s*unix_sock_rw_perms.*$'
    line: 'unix_sock_rw_perms = "0770"'
  notify: Reload libvirtd service

- name: Allow non-root users to libvirt unix_sock_admin_perms
  tags: [libvirt_setup, libvirt_user_mode]
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: '^#\s*unix_sock_admin_perms.*$'
    line: 'unix_sock_admin_perms = "0700"'
  notify: Reload libvirtd service