---
- name: Add user to libvirt group
  user:
    name: "{{ admin_user }}"
    groups: libvirt,qemu
    append: yes

- name: Allow non-root users to libvirt unix_sock_group
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: '^#\s*unix_sock_group.*$'
    line: 'unix_sock_group = "libvirt"'
  notify: Reload libvirtd service

- name: Allow non-root users to libvirt unix_sock_rw_perms
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: '^#\s*unix_sock_rw_perms.*$'
    line: 'unix_sock_rw_perms = "0770"'
  notify: Reload libvirtd service

- name: Allow non-root users to libvirt unix_sock_admin_perms
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    regexp: '^#\s*unix_sock_admin_perms.*$'
    line: 'unix_sock_admin_perms = "0700"'
  notify: Reload libvirtd service