---
- name: Verify IBM Power Systems Architecture
  command: grep -c -E 'POWER8' /proc/cpuinfo
  changed_when: False
  failed_when: False
  register: result

- name: Set a fact about  IBM Power Systems Architecture
  set_fact:
    libvirt_host_vt_enabled: "{{ result.rc == 0 }}"

- name: Notify if NOT POWER8  IBM Power Systems Architecture
  debug:
    msg: >
      This machine currently does not have POWER8 CPU
  when: not libvirt_host_vt_enabled


